name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10
    
    - name: Install and Build Nuxt Variant 6
      run: |
        cd variant6-nuxt
        pnpm install
        pnpm run generate
        mkdir -p dist
        cp -r .output/public/* dist/
        cd ..
    
    - name: Install and Build Nuxt Variant 7 (Images)
      run: |
        cd variant7-nuxt-images
        pnpm install
        pnpm run generate
        mkdir -p dist
        cp -r .output/public/* dist/
        cd ..
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      id: deployment
      uses: actions/deploy-pages@v4

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false